arch = [
    "alsa-utils",
    "altair",
    "android-udev",
    "baobab",
    "base",
    "base-devel",
    "bind",
    "bluez-tools",
    "btrfs-progs",
    "ccid",
    "cheese",
    "cpupower",
    "croc",
    "difftastic",
    "dmidecode",
    "doctl",
    "dosfstools",
    "downgrade",
    "dragon-drop",
    "dust",
    "efibootmgr",
    "element-desktop",
    "eog",
    "epiphany",
    "evince",
    "exfatprogs",
    "fakechroot",
    "firefox",
    "fprintd",
    "fzf",
    "gdb",
    "gdm",
    "gedit",
    "ghex",
    "gimp",
    "gnome-backgrounds",
    "gnome-calculator",
    "gnome-calendar",
    "gnome-characters",
    "gnome-clocks",
    "gnome-color-manager",
    "gnome-connections",
    "gnome-console",
    "gnome-contacts",
    "gnome-control-center",
    "gnome-disk-utility",
    "gnome-font-viewer",
    "gnome-keyring",
    "gnome-logs",
    "gnome-maps",
    "gnome-menus",
    "gnome-music",
    "gnome-photos",
    "gnome-remote-desktop",
    "gnome-session",
    "gnome-settings-daemon",
    "gnome-shell",
    "gnome-shell-extension-appindicator",
    "gnome-shell-extension-cpupower-git",
    "gnome-shell-extension-dash-to-dock",
    "gnome-shell-extensions",
    "gnome-software",
    "gnome-system-monitor",
    "gnome-terminal",
    "gnome-text-editor",
    "gnome-themes-extra",
    "gnome-tour",
    "gnome-tweaks",
    "gnome-user-docs",
    "gnome-user-share",
    "gnome-weather",
    "gnuplot",
    "google-chrome",
    "google-chrome-is-google-chrome-stable",
    "gparted",
    "grilo-plugins",
    "gsocket",
    "gst-plugin-pipewire",
    "gthumb",
    "gtk-engines",
    "gvfs",
    "gvfs-afc",
    "gvfs-goa",
    "gvfs-google",
    "gvfs-gphoto2",
    "gvfs-mtp",
    "gvfs-nfs",
    "gvfs-smb",
    "helvum",
    "htop",
    "i7z",
    "inetutils",
    "inkscape",
    "intel-media-driver",
    "intel-ucode",
    "iwd",
    "jq",
    "languagetool",
    "languagetool-user-service",
    "leiningen",
    "libfido2",
    "libguestfs",
    "libpulse",
    "libreoffice-fresh",
    "libthemis",
    "linux",
    "linux-firmware",
    "linux-lts",
    "linux-lts-headers",
    "list-packages-hook",
    "localsearch",
    "malcontent",
    "man-db",
    "man-pages",
    "masscan",
    "meld",
    "metapac",
    "moreutils",
    "mpv",
    "nano",
    "nano-syntax-highlighting",
    "nasm",
    "nautilus",
    "ncdu",
    "neofetch",
    "nethogs",
    "networkmanager",
    "nmap",
    "nvm",
    "obs-studio",
    "obsidian",
    "omnikey_ifdokccid",
    "openbsd-netcat",
    "openresolv",
    "opensc",
    "openssh",
    "openssl-1.1",
    "orca",
    "pandoc-cli",
    "papirus-icon-theme",
    "patchelf",
    "pcsc-tools",
    "pdfgrep",
    "perf",
    "perl-archive-zip",
    "perl-image-exiftool",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "plocate",
    "postgresql",
    "powerstat",
    "powertop",
    "pritunl-client-electron",
    "pv",
    "pyenv",
    "python-passlib",
    "python-pip",
    "python-pycryptodome",
    "remmina",
    "ripgrep",
    "rmtrash",
    "rsync",
    "ruff",
    "rustup",
    "rygel",
    "sassc",
    "screen",
    "sd",
    "seahorse",
    "simple-scan",
    "slack-desktop",
    "smartmontools",
    "snapper",
    "socat",
    "sof-firmware",
    "stlink",
    "strace",
    "sushi",
    "swig",
    "systray-x-common",
    "task",
    "tcpdump",
    "thunderbird",
    "tk",
    "tokei",
    "totem",
    "traceroute",
    "tree",
    "tuned",
    "tuned-ppd",
    "ufw",
    "usbguard",
    "usbutils",
    "vim",
    "wget",
    "whois",
    "wireless_tools",
    "wireplumber",
    "wl-clipboard",
    "wolfssl",
    "xdg-desktop-portal-gnome",
    "xdg-user-dirs-gtk",
    "xdg-utils",
    "yay",
    "yelp",
    "yt-dlp",
    "zip",
    "zoom",
]
