arch = [
    "alacritty",
    "bat",
    # For appsec http proxying
    "burpsuite",
    "arcanist",
    "clang",
    "cmake",
    "cmake3-bin",
    "docker",
    "docker-buildx",
    "docker-compose",
    "drawio-desktop",
    "fish",
    "flutter",
    "git",
    "git-lfs",
    "grpc-cli",
    "go",
    "ipython",
    "localsend-bin",
    "mkcert",
    "ninja",
    "paru",
    "pnpm",
    "pyside6",
    "python313",
    "python312",
    "python311",
    "python310",
    "python39",

    # download and setup VMs
    "quickemu-git",

    "rpi-imager",

    # Screenshots
    "satty",
    "starship",
    "swtpm",

    # Linter for shell files
    "shellcheck",

    # for tldr
    "tealdeer",
    "tpm2-tools",
    "uv",

    "virtualbox",
    "virtualbox-guest-iso",
    "virtualbox-host-modules-arch",

    "visual-studio-code-bin",

    "wireshark-qt",
    "yubico-piv-tool",
    "yubikey-manager",

    "zellij",
    "zoxide",
]
