arch = [
    "alacritty",
    "bat",
    # For appsec http proxying
    "burpsuite",
    "arcanist",
    "clang",
    "cmake",
    "cmake3-bin",
    "docker",
    "docker-buildx",
    "docker-compose",
    "drawio-desktop",
    "fish",
    "flutter",
    "git",
    "git-lfs",
    "grpc-cli",
    "go",
    "ipython",
    "localsend-bin",
    "mkcert",
    "ninja",
    "paru",
    "pnpm",
    "pyside6",
    "python312",
    "python39",
    "rpi-imager",
    "sqlitebrowser",
    "starship",
    "step-ca",
    "step-cli",
    "swtpm",
    # for tldr
    "tealdeer",
    "tpm2-tools",
    "uv",
    "vagrant",
    "virtualbox",
    "virtualbox-guest-iso",
    "virtualbox-host-modules-arch",
    "visual-studio-code-bin",
    "wabt",
    "wasm-tools",
    "wasmtime",
    "wireshark-qt",
    "yubico-piv-tool",
    "yubikey-manager",
    "zellij",
    "zoxide",
]
